const official=[['Official Neverway site','https://neverwaygame.com/'],['Neverway on Steam','https://store.steampowered.com/app/2318330/Neverway/'],['Official Steam news','https://steamcommunity.com/app/2318330/allnews/']];
const patches=[['Neverway Steam Community','https://steamcommunity.com/app/2318330'],['Prologue Patch 3','https://steamcommunity.com/ogg/2318330/announcements/detail/529876585129447807'],['Official Neverway FAQ','https://neverwaygame.com/']];

export const phase2Pages=[
{path:'prologue',label:'Prologue',eyebrow:'Playable Story Preview',title:'Neverway Prologue Walkthrough Overview and Content Guide',description:'Understand the Neverway Prologue structure, Fiona’s opening, the simulation, Fang, combat training, technical fixes, and its relationship to the full game.',answer:'The free Neverway Prologue is a two-part preview: it introduces Fiona’s life before Montgomery Island, then jumps to a disorienting simulation segment that previews combat and exploration.',sections:[
['Fiona’s opening','<p>The opening follows Fiona while work, relationships, and her ability to cope are breaking down. The player completes ordinary tasks, retrieves belongings, makes dialogue choices, and experiences the incident that redirects her life. It is narrative setup, not a shortened farming sandbox.</p><p>Dialogue can identify whether Fiona is telling the truth, but the Prologue does not explain every long-term consequence. Avoid treating each response as a permanent romance or ending decision before the full game can be checked.</p>'],
['The simulation','<p>The second section moves into a <a href="/world/simulation/">simulated environment</a> guided by <a href="/characters/fang/">Fang</a>. It introduces sword attacks, dodging, enemies, exploration, and a hook-style traversal tool. Public previews describe it as a look at a later part of Neverway rather than the next ordinary day after the opening.</p>'],
['What the preview proves','<p>Use the Prologue to test story tone, controls, mouse binding, performance, and combat feel. The full game is planned for October 2026 and is estimated at about 20 hours for the main story. Save import is not announced, so treat the preview and final release as separate builds.</p>']],faq:[['Is the Prologue the start of the final game?','It includes Fiona’s opening but also jumps to a later simulation segment.'],['Does it include the full farm loop?','No.'],['Who guides Fiona in the simulation?','Fang.']],sources:official},

{path:'updates',label:'Updates',eyebrow:'Official Patch Tracker',title:'Neverway Prologue Patch Notes and Update History',description:'Track Neverway Prologue patches for DirectX crashes, Vulkan and D3D11 options, IJKL rebinding, macOS reporting, progression fixes, visuals, and localization.',answer:'The latest prominently published Prologue update is Patch 4 from April 20, 2026. It followed Patch 3’s launch work with input, macOS, visual, progression, audio, and localization changes.',sections:[
['Patch 4 highlights','<p><a href="/demo/patch-4/">Patch 4</a> added IJKL movement rebinding, improved macOS crash reporting, and attempted fixes for a small-window snap-resolution crash, occasional black palette color, and getting stuck after leaving the apartment bathtub. It also corrected Fiona sitting on the simulation bench and music pacing near the fishing area.</p>'],
['Patch 3 highlights','<p><a href="/demo/patch-3/">Patch 3</a> updated graphics libraries in response to <a href="/demo/directx-12-crash/">DirectX 12 boot crashes</a>. The developers published Vulkan and D3D11 Steam launch options and noted Windows 11 Smart App Control as another possible blocker. It also fixed item duplication, email dates, mouse confinement, enemy respawning, and localization strings.</p>'],
['Using the tracker','<p>Check Steam news before applying an older workaround because the Prologue updates automatically. A useful bug report includes operating system, GPU, patch date, location, input method, and whether Vulkan or D3D11 was forced.</p>']],faq:[['What is the latest tracked patch?','Patch 4, published April 20, 2026.'],['Where are official notes posted?','The Neverway Steam Community news feed.']],sources:patches},

{path:'controls',label:'Controls',eyebrow:'Verified Input Hub',title:'Neverway Controls: Keyboard, Mouse, Controller, and Rebinding',description:'Configure Neverway Prologue keyboard, mouse, and controller inputs, remap controls, use IJKL movement, and troubleshoot reversed confirm or cancel buttons.',answer:'Neverway Prologue supports customizable input. Open Options, Gameplay, then Controls to rebind keyboard, controller, or mouse buttons; Patch 4 added IJKL movement rebinding.',sections:[
['Change bindings','<p>Return to the main menu, open Options, choose Gameplay, and enter Controls. Select the action and press the replacement input. Verify movement, interaction, attack, dodge, confirm, cancel, and menu navigation before resuming the story.</p>'],
['Keyboard and mouse','<p>Steam describes combat as optimized for keyboard or controller. The official FAQ confirms mouse-button binding, while Patch 3 keeps the pointer inside the game window when a control uses it. Patch 4 specifically added support for rebinding IJKL as movement keys.</p>'],
['Controller troubleshooting','<p>If confirm and cancel feel reversed on an Xbox-style layout, remap them in the game first. If prompts do not match the device, inspect Steam Input and disconnect unused controllers. PC controller support does not confirm an Xbox console release.</p>']],faq:[['Can controls be changed?','Yes, under Options → Gameplay → Controls.'],['Can mouse buttons be bound?','Yes.'],['Can I use IJKL?','Yes, after Patch 4.']],sources:patches},

{path:'characters',label:'Characters',eyebrow:'Verified Character Hub',title:'Neverway Characters: Fiona, Fang, Relationships, and Routines',description:'Meet confirmed Neverway characters, starting with protagonist Fiona and simulation guide Fang, and understand routines, relationships, buffs, and romance.',answer:'Fiona is Neverway’s fixed protagonist. Fang guides her in the Prologue simulation. The full game promises more than 10 characters with routines and storylines who can be befriended or dated.',sections:[
['Fiona','<p><a href="/characters/fiona/">Fiona</a> leaves a collapsing city life and begins again on a farm before becoming the immortal herald of a dead god. She is the only playable protagonist announced; there is no character creator. Her choices, relationships, daily routine, and combat abilities shape the journey.</p>'],
['Fang','<p><a href="/characters/fang/">Fang</a> appears as Fiona’s guide inside the simulated part of the Prologue. The sequence teaches combat and exploration while withholding their connection and the simulation’s purpose. Visible actions can be documented, but fan theories should not be presented as story canon.</p>'],
['Relationships and routines','<p>Official descriptions promise 10+ characters with unique routines and stories. Characters work, eat breakfast, oversleep, attend game nights, or share picnics. Bonds unlock buffs and combat abilities, and the game contains information showing whether someone is dateable.</p>']],faq:[['Who is the protagonist?','Fiona.'],['Who is Fang?','A mysterious simulation guide.'],['How many relationship characters are planned?','More than 10.']],sources:official},

{path:'combat',label:'Combat',eyebrow:'Confirmed Mechanics',title:'Neverway Combat Guide: Sword, Dodge, Abilities, and Grappling Hook',description:'Learn Neverway’s confirmed combat structure: top-down sword attacks, dodge movement, crafted items, relationship abilities, and grappling-hook traversal.',answer:'Neverway uses fast-paced top-down action combat. The Prologue simulation demonstrates sword attacks, dodging, enemies, and a hook-style tool for crossing gaps.',sections:[
['Basic loop','<p>Fiona fights in real time rather than through turn-based menus. The Prologue teaches a direct attack and dodge-focused loop, so spacing, recovery, and recognizing enemy movement matter more than farm statistics during these sequences.</p>'],
['Build customization','<p>The official Steam description says crafted items customize playstyle, while friendship bonds unlock buffs and combat abilities. Exact damage, cooldowns, optimal builds, and a full weapon list require final-game testing and are not inferred from trailers.</p>'],
['Traversal','<p>Public previews show a grappling-hook-style tool crossing gaps during the simulation. It supports exploration and player expression rather than proving a complete equipment tier. Combat connects to the nightmare reality that is leaking into Fiona’s world.</p>']],faq:[['Is combat turn based?','No.'],['Do relationships unlock abilities?','Yes.'],['Is a hook tool shown?','Yes, in public Prologue coverage.']],sources:official},

{path:'farming',label:'Farming',eyebrow:'Confirmed Life Sim',title:'Neverway Farming Guide: Time Blocks, Crops, Crafting, and Story Role',description:'Understand Neverway farming before launch, including morning, afternoon, and evening blocks, crops, crafting, meals, decorating, and story progression.',answer:'Farming is confirmed, but Neverway is primarily a story-led RPG rather than an endless farm sandbox. Time advances through morning, afternoon, and evening when the player chooses.',sections:[
['Time structure','<p>Neverway does not use an always-running clock in its official description. A day is divided into morning, afternoon, and evening, and the player chooses when to advance. This supports deliberate decisions about farming, relationships, exploration, and story tasks.</p>'],
['Connected systems','<p>The full game includes farming, fishing, crafting, preparing meals, and decorating the homestead. Crops and gathered materials can therefore connect to food, crafted equipment, gifts, money, or preparation for dangerous exploration.</p>'],
['Story boundary','<p>The developers estimate a roughly 20-hour main story with optional detours and emphasize that the game has an ending. Crop calendars, profit rankings, growth days, and seed prices remain outside the index until verified against the final build.</p>']],faq:[['Is Neverway endless?','No. It is primarily a story game.'],['Does time always run?','The player chooses when to advance between three blocks.'],['Can you decorate?','Yes.']],sources:official},

{path:'romance',label:'Romance',eyebrow:'Relationship Hub',title:'Neverway Romance Guide: Dateable Characters, Bonds, and Buffs',description:'Learn what is confirmed about Neverway romance: 10+ characters, unique routines, dateability information, relationship stories, buffs, and combat abilities.',answer:'Neverway allows Fiona to meet or date more than 10 characters. Each has a routine and storyline, and stronger bonds can unlock buffs or combat abilities.',sections:[
['Dateable characters','<p>The developers say dateability information can already be found inside the game, but they have not published a complete official romance list in the sources used here. A character page identifies a route only when the interface or final build confirms it.</p>'],
['Progression rewards','<p>Relationships are connected to progression rather than isolated dialogue collections. Each bond can unlock buffs and combat abilities. Dialogue can distinguish lies from truthful answers, suggesting that how Fiona presents herself matters to character stories.</p>'],
['Routines and events','<p>Characters have weekly routines such as working, eating breakfast, oversleeping, game nights, and picnics. The team previously described around 150 implemented routine interactions. Exact gifts, birthdays, event thresholds, and endings wait for direct verification.</p>']],faq:[['Can Fiona date characters?','Yes.'],['Are all 10+ characters romanceable?','That is not stated.'],['Do bonds affect combat?','Yes.']],sources:official},

{path:'demo/patches',label:'Patches',eyebrow:'Prologue Update Hub',title:'Neverway Prologue Patches: Patch 3 and Patch 4 Fix Index',description:'Browse Neverway Prologue Patch 3 and Patch 4 changes for DirectX crashes, launch options, macOS reporting, IJKL controls, progression, visuals, and localization.',answer:'Patch 3 concentrated on DirectX 12 startup and gameplay bugs; Patch 4 followed with input, macOS reporting, small-window, progression, visual, audio, and localization fixes.',sections:[
['Patch 3','<p><a href="/demo/patch-3/">Patch 3</a> updated graphics libraries, published Vulkan and D3D11 workarounds, and highlighted Windows 11 Smart App Control. It also handled item duplication, incorrect email dates, mouse confinement, unintended Lancelot access, bridge enemy respawns, and localization.</p>'],
['Patch 4','<p><a href="/demo/patch-4/">Patch 4</a> added IJKL movement rebinding and improved macOS crash reporting. It attempted fixes for snap-resolution resizing, black palette color, and the apartment bathtub blocker, plus corrected bench sitting, fishing-area music, and localization feedback.</p>'],
['Choose a fix','<p>For a game that will not open, start with DirectX and launch-option guidance. For input, use the controls hub. For a location-specific blocker, confirm Steam has installed the newest Prologue update before repeating the sequence.</p><div class="related-grid"><a href="/demo/directx-12-crash/">DirectX 12 crash</a><a href="/demo/macos-crash/">macOS crash</a><a href="/demo/window-resize-crash/">Window resize crash</a><a href="/demo/stuck-after-bathtub/">Bathtub blocker</a><a href="/demo/ijkl-controls/">IJKL controls</a><a href="/demo/black-palette-fix/">Black palette</a><a href="/demo/bridge-enemies-respawn/">Bridge enemies</a><a href="/demo/item-duplication-fix/">Item duplication</a><a href="/demo/mouse-cursor-confined/">Mouse cursor</a></div>']],faq:[['Which patch added IJKL?','Patch 4.'],['Which addressed DirectX 12?','Patch 3.']],sources:patches},

{path:'demo/patch-3',label:'Patch 3',eyebrow:'Official Update',title:'Neverway Prologue Patch 3 Notes: DirectX, Mouse, and Bug Fixes',description:'Neverway Prologue Patch 3 updated graphics libraries, documented Vulkan and D3D11 launch fixes, and repaired duplication, dates, mouse, enemies, and localization.',answer:'Patch 3 was published April 13, 2026. Its main technical focus was DirectX 12 boot crashing, with updated graphics libraries and Vulkan or D3D11 launch options.',sections:[
['Startup changes','<p>The developers updated graphics libraries to remediate DirectX 12 boot crashes. They instructed affected players to test <code>/gldevice:Vulkan</code> or <code>/gldevice:D3D11</code> through Steam Properties and noted Windows 11 Smart App Control as a possible blocker.</p>'],
['Gameplay fixes','<p>The patch removed an item duplication method involving pause and chest opening, corrected email dates after reaching the island, stopped enemies near the bridge from respawning, and blocked unintended Lancelot access through virtual rendering.</p>'],
['Input and language','<p>When controls rely on the mouse, the game now keeps the pointer inside the window. Patch 3 also fixed Simplified Chinese and Spanish strings. Remaining problems should be reported with platform and input details.</p>']],faq:[['When was Patch 3 released?','April 13, 2026.'],['What launch options were documented?','Vulkan and D3D11.']],sources:patches},

{path:'demo/patch-4',label:'Patch 4',eyebrow:'Official Update',title:'Neverway Prologue Patch 4 Notes: IJKL, macOS, and Progression Fixes',description:'Neverway Prologue Patch 4 added IJKL rebinding and addressed macOS reporting, resizing, bathtub progression, bench sitting, palette, music, and localization.',answer:'Patch 4 was published April 20, 2026. It added IJKL movement rebinding and delivered crash-reporting, progression, visual, audio, and localization changes.',sections:[
['Input and macOS','<p>IJKL keys became supported for movement rebinding. On macOS, crash reporting was improved to investigate submitted crashes; the developers explicitly said this reporting change did not itself resolve those crashes.</p>'],
['Crash and progression','<p>The team possibly addressed a crash caused by resizing the window extremely small with snap resolution. It also possibly fixed Fiona getting stuck after leaving the apartment bathtub and stopped players from sneaking behind Lancelot.</p>'],
['Other corrections','<p>The notes mention an occasional black palette color, Fiona sitting correctly on the simulation bench, music pacing near the fishing area, and Spanish and Russian localization feedback. Steam should install the update before troubleshooting older behavior.</p>']],faq:[['When was Patch 4 released?','April 20, 2026.'],['Did it fix macOS crashes?','It improved reporting but did not claim a fix.'],['Which keys became rebindable?','IJKL.']],sources:patches},

{path:'demo/directx-12-crash',label:'DirectX 12 Crash',eyebrow:'Startup Fix',title:'Neverway Prologue DirectX 12 Crash: Vulkan and D3D11 Workaround',description:'Fix a Neverway Prologue DirectX 12 startup crash by updating the game and testing the official Vulkan or D3D11 Steam launch options separately.',answer:'Update the Prologue first, then test either /gldevice:Vulkan or /gldevice:D3D11 in Steam launch options. Patch 3 retained these workarounds for remaining boot crashes.',sections:[
['Add a launch option','<ol><li>Right-click Neverway Prologue in Steam.</li><li>Choose Properties, then General.</li><li>Enter <code>/gldevice:Vulkan</code> and launch.</li><li>If it fails, replace it with <code>/gldevice:D3D11</code>.</li></ol><p>Use one option at a time so the result is clear.</p>'],
['Check other blockers','<p>If both paths fail, inspect Windows Security history for Smart App Control, verify Steam files, update the graphics driver, and confirm minimum requirements. Do not disable a security feature unless Windows records it as the blocker.</p>'],
['Report the failure','<p>Include Windows version, GPU, driver, patch date, option tested, whether a black screen appears, and whether the process closes. This separates graphics initialization from security blocking and later loading problems.</p>']],faq:[['Should both options be combined?','No.'],['Did Patch 3 guarantee a fix?','No; workarounds were still provided.']],sources:patches},

{path:'features/time-system',label:'Time System',eyebrow:'Life Sim Mechanic',title:'How Neverway Time Works: Morning, Afternoon, and Evening Blocks',description:'Neverway divides each day into morning, afternoon, and evening and lets the player choose when to advance, supporting farming, relationships, and exploration.',answer:'Neverway uses three daily blocks—morning, afternoon, and evening—and the player chooses when to advance rather than watching an always-running clock.',sections:[
['Three-block day','<p>The official description frames time as deliberate blocks. This reduces pressure from a continuously ticking day and lets the player decide when an activity has used the current period. Exact action costs and exceptions require final-game verification.</p>'],
['Character routines','<p>NPCs follow weekly routines: they may work, eat breakfast, oversleep, attend game nights, or share picnics. Time of day and weekday can therefore affect where characters are and which social interactions are available.</p>'],
['Planning a day','<p>Farming, fishing, crafting, meals, relationships, and combat connect to story progression. A useful plan combines necessary story actions with one preferred system rather than maximizing every mechanic. Final schedules wait for the full calendar.</p>']],faq:[['How many blocks are there?','Three.'],['Does time always run?','No; the player chooses when to advance.'],['Do characters have schedules?','Yes.']],sources:official},

{path:'characters/fiona',label:'Fiona',eyebrow:'Protagonist',title:'Fiona in Neverway: Protagonist, Prologue Story, and Gameplay Role',description:'Learn who Fiona is in Neverway, why she leaves her old life, how the Prologue introduces her, and how farming, relationships, choices, and combat shape her story.',answer:'Fiona is Neverway’s fixed playable protagonist. After her city life collapses, she starts over on a farm and becomes the immortal herald of a dead god.',sections:[
['Prologue setup','<p>The Prologue presents Fiona at a low point involving work, isolation, and strained relationships. Ordinary tasks and dialogue choices communicate her mental state before a disturbing incident redirects her life.</p>'],
['Island life','<p>The full game connects Fiona’s farm, mortgage, meals, crafting, fishing, decorating, and relationships to a larger story. She can meet or date characters, and those bonds grant buffs or combat abilities.</p>'],
['Neverway','<p>Fiona becomes the immortal herald of a dead god while the nightmare reality called Neverway leaks into her world. The simulation previews her sword, dodge, and traversal tools. No alternate protagonist or character creator is announced.</p>']],faq:[['Can you create a protagonist?','No; Fiona is fixed.'],['Is Fiona playable in the Prologue?','Yes.']],sources:official},

{path:'characters/fang',label:'Fang',eyebrow:'Simulation Guide',title:'Who Is Fang in Neverway? Prologue Simulation Role Explained',description:'Fang is the mysterious guide in Neverway Prologue’s simulation, introducing Fiona to combat and exploration while the full relationship remains unexplained.',answer:'Fang guides Fiona inside the Prologue simulation. The preview establishes that role but intentionally withholds the full context of who Fang is and why the simulation exists.',sections:[
['Visible role','<p>After the grounded opening, the Prologue jumps to a simulated section. Fang guides Fiona while she learns to fight, dodge, explore, and use a hook-style traversal tool. It previews later mechanics rather than explaining every connection.</p>'],
['The mystery','<p>The Prologue does not fully define Fang’s relationship to Fiona, the simulation’s origin, or how the sequence fits the October release. Community theories are discussion, not confirmed biography or lore.</p>'],
['Reading the sequence','<p>Public previews connect the unstable environment to Fiona’s memories. Focus on explicit labels, Fang’s instructions, and visible glitches. Later pages should separate confirmed dialogue from interpretation and mark story spoilers.</p>']],faq:[['Is Fang playable?','No.'],['Is Fang completely explained?','No.'],['Who is playable?','Fiona.']],sources:[...official,['Nintendo Life preview','https://www.nintendolife.com/previews/feature-life-horror-and-a-bit-of-zelda-why-neverway-is-one-of-our-most-anticipated-games-of-2026']]},

{path:'world/simulation',label:'Simulation',eyebrow:'Prologue Location',title:'Neverway Prologue Simulation: Fang, Combat, and Story Context',description:'Understand the Neverway Prologue simulation, why it follows Fiona’s opening, what mechanics it teaches, and which story questions remain unanswered.',answer:'The simulation is the Prologue’s second major section. It jumps from Fiona’s opening story to an unstable environment where Fang guides combat and exploration training.',sections:[
['Abrupt transition','<p>The Prologue is designed to show both Neverway’s emotional narrative and action RPG side. The simulation does not behave like the next ordinary day after the opening; it exposes a different point in Fiona’s experience without complete context.</p>'],
['Mechanics','<p>Fiona uses a sword, dodge movement, and hook-like traversal device while encountering enemies and environmental obstacles. Patch notes also reference a simulation bench and corrected her sitting animation there.</p>'],
['Interpretation boundary','<p>Fang’s identity, the simulation’s operator, and its exact story position are not fully disclosed. Document visible instructions, environments, glitches, and mechanics while leaving theories labeled until the full game resolves them.</p>']],faq:[['Who guides the simulation?','Fang.'],['Why is it included?','To preview the action and mystery side.'],['Does it reveal the full plot?','No.']],sources:[...official,['Nintendo Life preview','https://www.nintendolife.com/previews/feature-life-horror-and-a-bit-of-zelda-why-neverway-is-one-of-our-most-anticipated-games-of-2026']]}
];

phase2Pages.push({path:'world',label:'World',eyebrow:'World and Story Hub',title:'Neverway World Guide: Montgomery Island, Simulation, and Nightmare Realm',description:'Explore the confirmed Neverway settings, including Fiona’s city opening, Montgomery Island, the Prologue simulation, and the nightmare reality leaking into her world.',answer:'Neverway moves between Fiona’s grounded life, her new farm on Montgomery Island, a mysterious simulation, and the nightmare reality called Neverway that is slowly leaking into the ordinary world.',sections:[
['Fiona’s city opening','<p>The Prologue begins with Fiona’s work and personal life collapsing. Apartments, streets, public transport, and her former workplace establish a grounded emotional setting before horror distorts the familiar environment.</p>'],
['Montgomery Island','<p>The full life-sim structure takes place around Fiona’s remote island home. Official materials show farming, fishing, Sellmart, homestead decoration, friendships, routines, meals, and mortgage pressure. Exact shop inventories and map routes wait for final-game verification.</p>'],
['Simulation and Neverway','<p>The Prologue jumps to a <a href="/world/simulation/">simulation</a> where <a href="/characters/fang/">Fang</a> guides Fiona through combat and traversal. Separately, Neverway is described as a nightmare reality leaking into her world. Their full relationship remains a story mystery, so location pages separate visible evidence from interpretation.</p>']],faq:[['Where does Fiona start?','In a city before moving to the island.'],['What is Montgomery Island?','The remote setting for her new farm and relationships.'],['Is the simulation fully explained?','No.']],sources:official});
