const official=[['Official Neverway site','https://neverwaygame.com/'],['Neverway on Steam','https://store.steampowered.com/app/2318330/Neverway/'],['Official Steam news','https://steamcommunity.com/app/2318330/allnews/']];
const patches=[['Neverway Steam Community','https://steamcommunity.com/app/2318330'],['Prologue Patch 3','https://steamcommunity.com/ogg/2318330/announcements/detail/529876585129447807'],['Official Neverway FAQ','https://neverwaygame.com/']];
const p=(path,label,title,description,answer,sections,faq,sources=official)=>({path,label,eyebrow:'Verified Guide',title,description,answer,sections,faq,sources});

export const phase3Pages=[
p('building','Building','Neverway Building Guide: Homestead Decoration and Crafted Items','Learn what building means in Neverway, including homestead decoration, crafted items, farm-life customization, and the boundary between confirmed features and unverified recipes.','Neverway confirms that Fiona can build a new life and decorate her homestead. Crafted items also customize combat playstyle, but exact buildings, recipes, costs, and upgrade tiers require final-game verification.',[
['Confirmed scope','<p>The official site presents building as part of Fiona’s new island life alongside farming, fishing, crafting, meals, and relationships. Screenshots show a homestead context, while Steam explicitly says players can decorate. This supports a housing and placement system without proving a town-builder mode.</p>'],
['Connection to crafting','<p>Crafted items influence playstyle and combat preparation, so building materials may compete with equipment or household uses. A useful launch guide will compare requirements, function, placement limits, and prerequisites instead of publishing empty recipe grids.</p>'],
['What remains closed','<p>No authoritative full list of structures, furniture, stations, material costs, upgrade levels, or town improvements is published in the sources used here. Those leaves stay outside the sitemap until the final build supplies concrete data and screenshots.</p>']],[['Can Fiona decorate her home?','Yes.'],['Is Neverway a town builder?','That is not an announced core mode.'],['Are building recipes published?','Not as a complete verified list.']]),

p('crafting','Crafting','Neverway Crafting Guide: Items, Materials, Combat, and Homestead Uses','Understand confirmed Neverway crafting, how crafted items customize combat and homestead life, and which recipe details remain unavailable before launch.','Crafting is a confirmed system used to create items and customize Fiona’s playstyle. It connects farm resources and exploration to combat, meals, tools, and the homestead.',[
['Why crafting matters','<p>Steam describes crafted items as a way to customize playstyle. This makes crafting more than a sell-value table: players may choose between immediate supplies, combat preparation, relationship needs, and longer-term homestead improvements.</p>'],
['Material loop','<p>Farming, fishing, exploration, and shops are likely material sources because all are confirmed connected systems. Exact drop rates, stations, recipes, and prices are not inferred. Each future recipe page must show ingredients, source, effect, unlock condition, and a practical use.</p>'],
['Combat connection','<p>Neverway also unlocks combat abilities through relationships. A build can therefore combine crafted items with bond rewards rather than relying on a single weapon ladder. Final recommendations wait for tested effects, cooldowns, and enemy encounters.</p>']],[['Is crafting confirmed?','Yes.'],['Does crafting affect combat?','Official descriptions say crafted items customize playstyle.'],['Are all recipes known?','No.']]),

p('cooking','Cooking','Neverway Cooking Guide: Meals, Farming, Gifts, and Preparation','Learn how preparing meals fits Neverway’s farm and life-sim loop, including crop use, exploration preparation, relationships, and the limits of pre-release recipe data.','Preparing meals is a confirmed Neverway activity. Cooking connects farming and gathered ingredients to daily planning, exploration preparation, and potentially social decisions.',[
['Confirmed activity','<p>Steam lists preparing meals beside farming, crafting, and decorating the homestead. The game’s three-block day means cooking may be a deliberate use of time or preparation between morning, afternoon, and evening activities.</p>'],
['Useful recipe data','<p>A quality recipe page needs exact ingredients, unlock source, effect, duration, sell value, and best use. Until those fields can be verified, this hub explains the system without inventing dishes or copying generic farming-game advice.</p>'],
['Relationships and combat','<p>Food may support exploration or social play, but exact healing values and character preferences are not published here. Official material confirms that bonds unlock buffs and combat abilities, while Patch 4 references music pacing near a fishing area rather than any specific recipe.</p>']],[['Can Fiona cook?','Yes, preparing meals is confirmed.'],['Are recipes available here?','Only after exact ingredients and effects can be verified.'],['Does cooking consume a time block?','Exact action costs are not yet verified.']]),

p('fishing','Fishing','Neverway Fishing Guide: Confirmed Activity, Time Blocks, and Uses','Understand confirmed Neverway fishing, how it fits island life and three daily time blocks, and what must be verified before publishing fish locations or value tables.','Fishing is a confirmed activity on Montgomery Island. It belongs to the same daily loop as farming, crafting, meals, relationships, and story exploration.',[
['How it fits the day','<p>Neverway divides time into morning, afternoon, and evening and lets the player choose when to advance. Fishing therefore competes with other activities by schedule rather than an always-running clock, though exact time costs are not yet documented.</p>'],
['Potential uses versus facts','<p>Fish may become ingredients, gifts, sales, or collection entries, but those uses require item-level evidence. This guide does not invent species, seasons, weather rules, rod upgrades, or prices from conventions in other life sims.</p>'],
['Prologue evidence','<p>Patch 4 specifically corrected music pacing near the fishing area, confirming that such an area exists in the Prologue content. A location walkthrough still needs direct play, route directions, and an answer to how equipment is obtained before indexing.</p>']],[['Is fishing confirmed?','Yes.'],['Are fish locations published?','Not until they are verified.'],['Did Patch 4 mention fishing?','Yes, it fixed music pacing near the fishing area.']]),

p('mortgage','Mortgage','Neverway Mortgage Guide: Payments, Money, and Story Pressure','Learn what is confirmed about Neverway’s mortgage, how payments connect to farming and island life, and why exact repayment schedules remain unavailable before launch.','Fiona must pay a mortgage while rebuilding her life on Montgomery Island. It creates economic pressure alongside farming, fishing, crafting, relationships, and the larger debt-to-a-dead-god story.',[
['Confirmed role','<p>The official site explicitly lists “Pay your mortgage” as a feature. This grounds the economy in a recurring obligation rather than limitless accumulation, but it does not publish payment amounts, deadlines, penalties, interest, or upgrade stages.</p>'],
['Earning decisions','<p>Farming, fishing, crafted items, meals, and shops are confirmed parts of island life. A launch economy guide should compare reliable income, required supplies, and payment timing without recommending that players sell unique or story-critical items.</p>'],
['Two kinds of debt','<p>The mortgage is ordinary financial pressure, while Fiona also becomes the immortal herald of a dead god and must face a supernatural debt. They should not be collapsed into one mechanic until the story explains their exact relationship.</p>']],[['Is there a mortgage?','Yes.'],['Are payment amounts known?','No verified schedule is published.'],['Is the mortgage the same as the debt to Death?','The official premise presents financial and supernatural pressures separately.']]),

p('sellmart','Sellmart','Neverway Sellmart Guide: Island Shop, Buying, and Verification Status','Learn what Sellmart is in Neverway, how the island shop may connect supplies and progression, and which inventory and price details remain unverified.','Sellmart is a named shopping location shown in official Neverway material. It supports Fiona’s island routine, but a complete stock list, prices, hours, and unlock rules are not yet officially published.',[
['What is confirmed','<p>The official website labels a screenshot “Buy at Sellmart,” making the shop and its commercial role concrete. It is appropriate to cover the location as an island service without fabricating who operates it or what every shelf contains.</p>'],
['What a shop guide needs','<p>A useful launch table should record item, price, availability, weekday or time block, stock limit, prerequisites, and best alternative source. Those fields prevent overlapping thin pages such as separate “where to buy” URLs with no distinct answer.</p>'],
['Early purchase logic','<p>Players will eventually compare seeds, tools, food, crafting materials, and upgrades against mortgage pressure. Until exact stock is verified, the safest advice is to preserve money for required progression and avoid pretending a trailer proves an optimal purchase order.</p>']],[['Is Sellmart official?','Yes.'],['Is its full inventory known?','No.'],['Where is it?','It is associated with Fiona’s island life; exact map directions need final-game verification.']]),

p('montgomery-island','Montgomery Island','Montgomery Island Guide: Farm, Sellmart, Routines, and Exploration','Explore confirmed Montgomery Island features in Neverway, including Fiona’s farm, Sellmart, homestead, character routines, fishing, relationships, and hidden dangers.','Montgomery Island is where Fiona starts her new farm life. It contains everyday systems such as farming, fishing, shopping, building, and relationships while the nightmare reality begins leaking into her world.',[
['Daily-life hub','<p>The island supports Fiona’s homestead, farm work, Sellmart shopping, fishing, meals, and mortgage. Time advances through morning, afternoon, and evening, giving locations and character routines different relevance across a day.</p>'],
['Residents and routines','<p>More than 10 characters have unique stories and routines. Developers have described work, breakfast, oversleeping, game nights, and picnics among roughly 150 implemented routine interactions. Exact schedules remain a launch-data task.</p>'],
['Horror beneath the routine','<p>Neverway is a nightmare reality slowly leaking into Fiona’s ordinary life. The island therefore should not be documented only as a cozy farm map; story progression, combat, secrets, and changing conditions are part of its identity.</p>']],[['Where is Fiona’s farm?','On Montgomery Island.'],['Is Sellmart on the island?','Official material associates it with island life.'],['Are resident schedules published?','Not as a complete verified database.']]),

p('neverway-realm','Neverway Realm','The Neverway Realm Guide: Nightmare Reality, Combat, and Story Role','Understand the nightmare reality called Neverway, how it leaks into Fiona’s world, and how combat, exploration, memory, and the dead god connect to the premise.','Neverway is the nightmare reality that is slowly leaking into Fiona’s world. Searching for it drives the horror story while Fiona also manages farm life, relationships, and combat.',[
['What the name means','<p>Neverway is not simply the title of the island or a generic dungeon label. Official descriptions call it a nightmare reality. Its intrusion creates the contrast between ordinary routines and the game’s psychological and supernatural horror.</p>'],
['Combat and exploration','<p>The game uses fast-paced top-down combat, crafted items, relationship abilities, and traversal tools. The Prologue simulation demonstrates some of these mechanics, but it does not fully establish whether every simulated area is literally part of Neverway.</p>'],
['Story boundary','<p>Fiona becomes the immortal herald of a dead god and is drawn into the search for Neverway. Exact realm rules, bosses, maps, chapter order, and endings remain spoiler-sensitive and require final-build evidence rather than theories.</p>']],[['Is Neverway the island?','No. It is described as a nightmare reality.'],['Does it involve combat?','Combat and horror exploration are central to the premise.'],['Is the simulation the same place?','Their exact relationship is not fully explained.']]),

p('demo/macos-crash','macOS Crash','Neverway Prologue macOS Crash Status and Reporting Guide','Understand Neverway Prologue’s macOS crash status after Patch 4, what improved crash reporting means, and what details to submit for a useful bug report.','Patch 4 improved macOS crash reporting but explicitly did not claim to fix the few reported crashes. Update first, reproduce once, and submit the resulting context through official support.',[
['Patch 4 status','<p>The developer said improved reporting would help investigate macOS crashes going forward. This is diagnostic work, not evidence that every crash was resolved. Do not label an issue fixed only because reporting changed.</p>'],
['Before reporting','<p>Install the latest Prologue update, restart Steam, verify game files, and note the exact macOS version and Mac model. Record whether the crash occurs at boot, on the dock or bridge, during resizing, or after a specific interaction.</p>'],
['Useful report fields','<p>Include Mac model, chip, memory, OS version, patch date, display mode, controller or keyboard use, last visible screen, and whether the issue repeats on a new launch. Use Steam forums or the official Discord named by the developers.</p>']],[['Did Patch 4 fix macOS crashes?','No; it improved reporting.'],['Where should I report one?','Steam or the official Discord.'],['Should I update first?','Yes.']],patches),

p('demo/window-resize-crash','Window Resize Crash','Neverway Prologue Window Resize Crash and Snap Resolution Fix','Fix or report a Neverway Prologue crash caused by shrinking the window with snap resolution, a problem Patch 4 said it had possibly addressed.','Patch 4 possibly addressed a crash caused by resizing the game window extremely small while using snap resolution. Update before retesting and avoid reducing the window to an unusable size.',[
['Known trigger','<p>The official note describes a very small resized window and “snap” resolution. It does not state that ordinary fullscreen switching always crashes, so preserve the exact trigger when searching or reporting.</p>'],
['Safe recovery','<p>Restart the game, use a normal window size, and avoid repeated rapid resize actions. If the game cannot reopen, verify files and test the developer’s Vulkan or D3D11 launch option separately only when startup itself is failing.</p>'],
['Report remaining cases','<p>Include desktop resolution, scale percentage, window mode, target size, GPU, operating system, and whether Patch 4 is installed. A short screen recording can distinguish snap behavior from a graphics-device boot crash.</p>']],[['Was the resize crash fixed?','Patch 4 says it was possibly addressed.'],['Is this the DirectX 12 issue?','It is a separate documented trigger.'],['What should I avoid?','Shrinking the window extremely small.']],patches),

p('demo/stuck-after-bathtub','Bathtub Stuck Fix','Neverway Prologue Stuck After Bathtub: Patch 4 Status','Learn the official status of the Neverway Prologue blocker after leaving the apartment bathtub and how to verify, retry, and report the sequence after Patch 4.','Patch 4 says it possibly fixed Fiona getting stuck immediately after leaving the bathtub in the apartment. Install the update before replaying the interaction.',[
['Verify the version','<p>Steam normally updates the Prologue automatically. Restart Steam or inspect downloads before repeating the apartment sequence. An old local build can preserve a blocker that the current patch attempted to address.</p>'],
['Retry carefully','<p>Load the most recent usable save, complete the bathtub interaction normally, and avoid changing window size or rapidly switching inputs during the exit. Record whether Fiona cannot move, the scene fails to advance, or the application freezes.</p>'],
['If it still happens','<p>Report patch date, operating system, input device, save origin, actions before entering the bathtub, and the exact stuck state. Do not promise a universal workaround because the official note only says the issue was possibly fixed.</p>']],[['Which patch addressed it?','Patch 4.'],['Is the fix guaranteed?','No; the note says possibly fixed.'],['Should I start over?','Update and test the latest usable save before discarding progress.']],patches),

p('demo/ijkl-controls','IJKL Controls','How to Use IJKL Movement Controls in Neverway Prologue','Use IJKL for movement in Neverway Prologue after Patch 4, find the rebinding menu, and diagnose bindings that do not save or display correctly.','Patch 4 added support for rebinding IJKL as movement keys. Open Options, Gameplay, Controls and assign each direction individually.',[
['Assign the keys','<p>From the main menu open Options, choose Gameplay, and enter Controls. Select movement up, left, down, and right, then bind I, J, K, and L. Apply changes and reopen the menu to verify them.</p>'],
['Test the layout','<p>Check movement during normal exploration and the simulation. Bind attack, dodge, interaction, confirm, and cancel around the same hand position if desired, while keeping every required menu action accessible.</p>'],
['Troubleshooting','<p>If a key is rejected, confirm Patch 4 is installed and remove conflicting duplicate bindings. Disconnect unused controllers if prompts switch unexpectedly. Report the language, keyboard layout, and exact action when a binding fails.</p>']],[['When was IJKL added?','Patch 4.'],['Where is rebinding?','Options → Gameplay → Controls.'],['Can other keys be remapped?','Customizable input is confirmed.']],patches),

p('demo/black-palette-fix','Black Palette Fix','Neverway Prologue Black Palette Color Bug: Patch 4 Status','Understand the occasional black palette color bug mentioned in Neverway Prologue Patch 4 and how to distinguish it from a black screen or startup crash.','Patch 4 says it possibly fixed an occasional black color in the palette. This is a visual palette issue, not automatically the same as a startup black screen.',[
['Identify the symptom','<p>Record whether the game is still responsive, music continues, UI remains visible, and only scene colors are wrong. A fully black, nonresponsive boot screen belongs to startup troubleshooting rather than this palette-specific report.</p>'],
['Update and retest','<p>Install Patch 4, reload the same area, and compare a new session. Avoid forcing display changes during the test because window resizing has its own documented crash history.</p>'],
['Report evidence','<p>Include area, time in the sequence, display mode, GPU, graphics device option, and a screenshot. The wording “possibly fixed” means a reproducible post-patch example remains useful to the developers.</p>']],[['Which patch mentioned the palette?','Patch 4.'],['Is it the same as a black-screen crash?','Not necessarily.'],['What evidence helps?','A screenshot plus location and graphics details.']],patches),

p('demo/bridge-enemies-respawn','Bridge Enemy Respawn','Neverway Prologue Bridge Enemies Respawning: Patch 3 Fix','Check the official fix for enemies near the bridge respawning in Neverway Prologue and what to report if the behavior still occurs after Patch 3.','Patch 3 states that enemies near the bridge no longer respawn. Update the Prologue before using an older route or repeatedly clearing the same group.',[
['What changed','<p>The fix is location-specific: it refers to enemies near the bridge. It does not establish a global rule that no enemy anywhere in Neverway can respawn.</p>'],
['Verify current behavior','<p>Install the latest build, approach through the normal route, defeat the group, leave the immediate area, and return once. Record whether the same enemies return after a scene change, reload, death, or full restart.</p>'],
['Report a regression','<p>Include patch date, exact bridge, route direction, enemies defeated, trigger used to leave, and whether the save predates Patch 3. This distinguishes a regression from intended encounters in another location.</p>']],[['Which patch fixed it?','Patch 3.'],['Does this apply to all enemies?','No; the note names enemies near the bridge.'],['Can an old save matter?','Include save origin when reporting a regression.']],patches),

p('demo/item-duplication-fix','Item Duplication','Neverway Prologue Item Duplication Fix: Pause and Chest Bug','Understand the Neverway Prologue item duplication bug involving pausing and opening a chest, and the official Patch 3 fix.','Patch 3 removed an item duplication exploit triggered by pausing and opening a chest at the same time. Current guides should not recommend it as a money or resource strategy.',[
['Original trigger','<p>The official note identifies simultaneous pause and chest opening as the duplication condition. It does not describe normal chest use as unsafe or prove that every inventory duplication method is related.</p>'],
['After updating','<p>Install the latest Prologue build and use chests normally. Items obtained through an old exploit may make progression or economy testing unreliable, so reproduce guides on an unmodified save when accuracy matters.</p>'],
['Why the page remains useful','<p>Players searching after seeing an old clip need a direct status answer. The exploit is fixed according to Patch 3, and this page prevents stale advice from being mistaken for a supported farming method.</p>']],[['Is the duplication exploit active?','Patch 3 says it was fixed.'],['What caused it?','Pausing while opening a chest.'],['Should guides recommend it?','No.']],patches),

p('demo/mouse-cursor-confined','Mouse Cursor','Neverway Prologue Mouse Cursor Locked to Window: Patch 3 Behavior','Understand why Neverway Prologue confines the mouse cursor to its window when mouse-based controls are active and how to adjust bindings.','Patch 3 intentionally forces the cursor to remain inside the game window when any active control relies on the mouse. This can be expected behavior rather than a crash.',[
['Why it happens','<p>Mouse confinement prevents the pointer leaving the game during actions, especially in windowed play. The patch note ties the behavior to control bindings that use the mouse rather than declaring permanent confinement for every setup.</p>'],
['Change the setup','<p>Open Options, Gameplay, Controls and review which actions use mouse buttons. Rebind those actions to keyboard or controller inputs, apply changes, and restart the scene to test whether confinement changes.</p>'],
['Report unexpected behavior','<p>If the cursor remains trapped in menus or after removing all mouse bindings, record window mode, operating system, active devices, Steam Input status, and the actions previously assigned. Distinguish intended gameplay confinement from inability to access menus.</p>']],[['Which patch added confinement?','Patch 3.'],['Is it always a bug?','No; it is intentional when controls rely on the mouse.'],['Where can bindings change?','Options → Gameplay → Controls.']],patches),

p('features/languages','Languages','Neverway Languages: English, Japanese, Chinese, Spanish, Portuguese, and Russian','Check Neverway’s currently listed Steam languages, subtitle and interface status, and which Patch 3 and Patch 4 localization changes affected the Prologue.','Steam currently lists interface and subtitle support for English, Japanese, Brazilian Portuguese, Simplified Chinese, Spanish from Spain, and Russian. Full audio is not marked.',[
['Steam language table','<p>The current store listing shows six supported languages for interface and subtitles. Store data can change before October, so final PC and Switch language coverage should be checked separately at launch.</p>'],
['Prologue patches','<p>Patch 3 corrected Simplified Chinese and Spanish localization strings. Patch 4 addressed additional Spanish and Russian feedback. These fixes describe the Prologue build rather than proving identical text or patch timing on Switch.</p>'],
['What is not listed','<p>Steam does not mark full audio for the six languages in the current listing. Other requested languages, regional variants, and platform parity remain unsupported as claims until a storefront or developer announcement adds them.</p>']],[['How many Steam languages are listed?','Six.'],['Is Simplified Chinese supported?','Yes, for interface and subtitles.'],['Is full voice acting marked?','No.']],official),

p('features/steam-cloud','Steam Cloud','Does Neverway Support Steam Cloud, Achievements, and Family Sharing?','Check Neverway’s listed Steam features, including Steam Cloud, achievements, Family Sharing, single-player mode, and the difference between cloud saves and Prologue carryover.','Steam lists Neverway with Steam Cloud, Steam Achievements, Family Sharing, and Single-player. These store features do not confirm Prologue save import into the full game.',[
['Cloud saves','<p>Steam Cloud can synchronize supported save data between compatible Steam installations. It does not automatically merge separate applications or guarantee that a Prologue save format will be accepted by the October release.</p>'],
['Achievements','<p>Steam Achievements are listed for the full game, but the final achievement names and requirements are not published in the sources used here. Achievement pages remain outside the sitemap until they provide exact unlock conditions.</p>'],
['Family Sharing and mode','<p>Family Sharing and Single-player are also listed. No co-op or multiplayer feature appears on the store page. Store capabilities can be revised, so this status page records the current listing rather than promising permanent availability.</p>']],[['Does Neverway use Steam Cloud?','It is listed on Steam.'],['Does that confirm Prologue carryover?','No.'],['Are achievements planned?','Steam Achievements are listed.']],official)
];
